name: Test

on:
  # Trigger at every push. Action will also be visible from Pull Requests to master
  push: # Comment this line to trigger action only on pull-requests (not recommended if you don't pay for GH Actions)
  pull_request:
    branches: [master]

permissions: read-all

jobs:
  build:
    name: Test
    permissions:
      contents: read
      id-token: write
      issues: write
      pull-requests: write

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java_version: [11, 17, 19]
    runs-on: ${{ matrix.os }}

    steps:
    # Git Checkout
    - name: Checkout Code
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Setup AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Setup Java ${{matrix.java_version}}
      uses: actions/setup-java@v4
      with:
        java-version: ${{matrix.java_version}}
        distribution: 'temurin'
        architecture: x64
        cache: gradle
       
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Run Gradle Tests
      run: ./gradlew check

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: quiltcore-java-test-reports
        path: |
          /home/runner/work/quiltcore-java/quiltcore-java/plugins/quiltcore-java/build/reports/tests/test/
